name: Release v1

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Zip Repository
        run: zip -r apk-autorelease.zip . -x .git* .github/workflows/*

      - name: Buat atau Update Tag dan Rilis
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1
          name: Release v1
          files: ./apk-autorelease.zip
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
