name: Release v1

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip Repository
        run: zip -r apk-autorelease.zip . -x .git*

      - name: Buat atau Update Tag dan Rilis
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1
          release_name: Release v1
          draft: false
          prerelease: false
          replace: true # Ganti tag yang sudah ada

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apk-autorelease.zip
          asset_name: apk-autorelease-v1.zip
          asset_content_type: application/zip
